const {_electron:electron}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const http=require('node:http');const yazl=require('yazl');const {pipeline}=require('node:stream/promises');
(async()=>{const temp=await fs.mkdtemp(path.join(os.tmpdir(),'odm-features-ui-'));const artifacts=path.join(__dirname,'../test-results');await fs.mkdir(artifacts,{recursive:true});const zip=new yazl.ZipFile();zip.addBuffer(Buffer.from('Archive UI fixture'),'nested/readme.txt');zip.end();const zipfile=path.join(temp,'fixture.zip');await pipeline(zip.outputStream,require('node:fs').createWriteStream(zipfile));const zipdata=await fs.readFile(zipfile);const video=await fs.readFile(require('./generate-fixture.cjs'));const {default:createTorrent}=await import('create-torrent');const tb=Buffer.from('Torrent UI fixture');tb.name='fixture.txt';let torrent;const makeTorrent=()=>new Promise((resolve,reject)=>createTorrent(tb,{private:true,announce:[],urlList:[base+'/fixture.txt']},(e,d)=>e?reject(e):resolve(Buffer.from(d))));const s=http.createServer((req,res)=>{if(req.url==='/page'){res.setHeader('content-type','text/html');res.end('<title>UI collection</title><video src="/a.mp4"></video><video src="/b.mp4"></video>');return;}const data=req.url.endsWith('.txt')?tb:req.url.endsWith('.torrent')?torrent:req.url.endsWith('.mp4')?video:zipdata;const m=/bytes=(\d+)-(\d*)/.exec(req.headers.range||'');const start=m?+m[1]:0,end=m&&m[2]?+m[2]:data.length-1;res.writeHead(m?206:200,{'content-length':end-start+1,etag:'"fixture"','content-type':req.url.endsWith('.mp4')?'video/mp4':'application/octet-stream',...(m?{'content-range':`bytes ${start}-${end}/${data.length}`}:{})});res.end(data.subarray(start,end+1));});await new Promise(r=>s.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${s.address().port}`;torrent=await makeTorrent();let app;
try{
 const env={...process.env,ODM_TEST_DATA:path.join(temp,'data'),ODM_TEST_PORT:'0'};delete env.ELECTRON_RUN_AS_NODE;app=await electron.launch({...(process.env.ODM_TEST_EXE?{executablePath:process.env.ODM_TEST_EXE,args:[]}:{args:[path.resolve(__dirname,'..')]}),env});const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('#empty-state');await page.waitForFunction(()=>!!window.odm);await page.evaluate(directory=>window.odm.invoke('settings',{downloadDir:directory}),path.join(temp,'downloads'));
 async function tool(command){await page.click('[data-menu="tools"]');await page.click(`#menu [data-command="${command}"]`);}
 async function snapshot(){return page.evaluate(()=>window.odm.invoke('snapshot'));}async function until(fn){const deadline=Date.now()+60000;while(!await fn()){if(Date.now()>deadline)throw Error('UI state timeout: '+JSON.stringify(await snapshot()));await new Promise(r=>setTimeout(r,100));}}
 await tool('collector');await page.fill('#collect-text',`Some text ${base}/fixture.zip and ${base}/fixture.zip`);await page.fill('#collect-package','Fixture package');await page.click('#collect-add');await page.waitForSelector('[data-collected]');await page.click('#collect-check');await page.waitForFunction(()=>document.querySelector('#collector-inbox').textContent.includes('online'));assert.equal((await snapshot()).inbox.length,1);await page.screenshot({path:path.join(artifacts,'12-link-collector.png')});await page.getByRole('button',{name:'Start selected',exact:true}).click();await until(async()=>{const s=await snapshot();return s.jobs[0]?.status==='complete' && s.jobs[0]?.output;});let state=await snapshot();assert.equal(state.jobs[0].package,'Fixture package');assert.deepEqual(await fs.readFile(state.jobs[0].output),zipdata);
 await page.locator('#rows tr').first().click();await tool('archive');await page.waitForSelector('[data-archive-index]');await page.fill('#archive-password','fixture');await page.click('#archive-read');await page.waitForFunction(()=>document.querySelector('#archive-entries').textContent.includes('readme.txt'));await page.screenshot({path:path.join(artifacts,'13-archive-contents.png')});await page.getByRole('button',{name:'Extract selected',exact:true}).click();await until(async()=>!!(await snapshot()).jobs[0].extractedTo);state=await snapshot();assert.equal(await fs.readFile(path.join(state.jobs[0].extractedTo,'nested/readme.txt'),'utf8'),'Archive UI fixture');
 await tool('mediaPrefs');await page.check('#smart-enabled');await page.selectOption('#media-quality','1080');await page.selectOption('#media-container','mkv');await page.fill('#media-subs','en');await page.getByRole('button',{name:'Save',exact:true}).click();assert.equal((await snapshot()).settings.media.quality,'1080');
 await tool('traffic');await page.check('[name="traffic"][value="browsing"]');await page.getByRole('button',{name:'Apply',exact:true}).click();assert.equal((await snapshot()).settings.speedLimit,256);
 await tool('rules');await page.click('#rule-new');await page.fill('[data-rule-field="host"]','127.0.0.1');await page.fill('[data-rule-field="extensions"]','pdf');await page.fill('[data-rule-field="package"]','Research');await page.getByRole('button',{name:'Save rules',exact:true}).click();assert.equal((await snapshot()).rules[0].package,'Research');
 await tool('library');await page.fill('#collection-url',base+'/page');await page.click('#collection-inspect');await page.waitForSelector('[data-media-index]',{timeout:120000});assert.equal(await page.locator('[data-media-index]').count(),2);await page.screenshot({path:path.join(artifacts,'14-media-library.png')});await page.getByRole('button',{name:'Download later',exact:true}).click();state=await snapshot();assert.equal(state.jobs.filter(j=>j.type==='video').length,2);assert.deepEqual(state.jobs.filter(j=>j.type==='video').map(j=>j.playlistItem),[1,2]);
 await tool('subscriptions');await page.fill('#sub-name','Test channel');await page.fill('#sub-url',base+'/page');await page.uncheck('#sub-enabled');await page.getByRole('button',{name:'Add subscription',exact:true}).click();await page.waitForSelector('[data-sub-check]');assert.equal((await snapshot()).subscriptions[0].enabled,false);await page.click('#dialog-close');
 await tool('torrent');await page.fill('#torrent-url',base+'/fixture.torrent');await page.click('#torrent-inspect');await page.waitForSelector('[data-torrent-file]',{timeout:60000});await page.screenshot({path:path.join(artifacts,'15-torrent-file-selection.png')});await page.getByRole('button',{name:'Download later',exact:true}).click();state=await snapshot();const tj=state.jobs.find(j=>j.type==='torrent');assert.equal(tj.status,'paused');await page.evaluate(id=>window.odm.invoke('resume',id),tj.id);await until(async()=>{const j=(await snapshot()).jobs.find(j=>j.id===tj.id);if(j.status==='error')throw Error(j.error);return j.status==='complete';});state=await snapshot();assert.deepEqual(await fs.readFile(state.jobs.find(j=>j.id===tj.id).outputs[0].path),Buffer.from(tb));await tool('remoteZip');await page.fill('#remote-zip-url',base+'/fixture.zip');await page.click('#remote-zip-inspect');await page.waitForSelector('[data-remote-file]');await page.check('[data-remote-file]');await page.getByRole('button',{name:'Extract selected',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#remote-zip-status').textContent.includes('Saved 1 files'));await page.screenshot({path:path.join(artifacts,'16-remote-zip-selection.png')});assert.deepEqual(errors,[]);console.log('PASS: Electron UI link collector/check/start, package file integrity, archive selective extraction, Smart Mode, traffic profile, rule editor, real yt-dlp media collection, paused subscription and torrent file selection, no renderer errors.');
}finally{await app?.close();s.closeAllConnections();await new Promise(r=>s.close(r));await fs.rm(temp,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
