const {Engine}=require('../src/engine.cjs');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const http=require('node:http');const assert=require('node:assert/strict');const {spawnSync}=require('node:child_process');
(async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'odm-advanced-media-'));const tools=require('../src/platform.cjs').developmentTools(path.resolve(__dirname,'..'));const engine=new Engine({dataDir:path.join(root,'data'),downloadDir:path.join(root,'downloads'),toolsDir:tools,ffmpegPath:require('../src/platform.cjs').toolPaths(tools).ffmpeg});engine.updateSettings({retries:0});const video=await fs.readFile(require('./generate-fixture.cjs'));const s=http.createServer((req,res)=>{if(req.url==='/playlist'){res.setHeader('content-type','text/html');res.end('<html><title>Fixture series</title><video controls src="/one.mp4"><track kind="subtitles" src="/en.vtt" srclang="en" label="English"></video><video controls src="/two.mp4"></video></html>');return;}if(req.url==='/en.vtt'){res.setHeader('content-type','text/vtt');res.end('WEBVTT\n\n00:00.000 --> 00:01.000\nFixture caption\n');return;}const m=/bytes=(\d+)-(\d*)/.exec(req.headers.range||'');const start=m?+m[1]:0,end=m&&m[2]?+m[2]:video.length-1;res.writeHead(m?206:200,{'content-type':'video/mp4','content-length':end-start+1,...(m?{'content-range':`bytes ${start}-${end}/${video.length}`}:{})});res.end(video.subarray(start,end+1));});await new Promise(r=>s.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${s.address().port}`;
  async function done(id){const deadline=Date.now()+120000;while(Date.now()<deadline){const j=engine.get(id);if(j.status==='error')throw Error(j.error);if(j.status==='complete')return j;await new Promise(r=>setTimeout(r,100));}throw Error('Media timeout');}
  function streams(file){const result=spawnSync(require('../src/platform.cjs').toolPaths(tools).ffprobe,['-v','error','-show_streams','-of','json',file],{encoding:'utf8',windowsHide:true});assert.equal(result.status,0,result.stderr);return JSON.parse(result.stdout).streams;}
  try{
    const collection=await engine.inspectCollection(base+'/playlist',10);console.log('Collection fixture:',JSON.stringify(collection));assert.equal(collection.entries.length,2);
    const added=engine.addCollection({...collection,start:false,media:{quality:'720'}});assert.equal(added.added,2);assert.equal(engine.jobs.length,2);
    const caption=engine.add({url:base+'/playlist',type:'video',media:{quality:'best',container:'mkv',subtitles:'en',metadata:true}});const j=await done(caption.id);assert.ok(streams(j.output).some(s=>s.codec_type==='video'));assert.ok(j.output.endsWith('.mkv'));assert.ok(j.sidecars.some(s=>s.endsWith('.srt')));assert.match(await fs.readFile(j.sidecars.find(s=>s.endsWith('.srt')),'utf8'),/Fixture caption/);
    const output=await engine.convertMedia(j.id,'mp3');assert.ok(streams(output).some(s=>s.codec_type==='audio'));assert.ok(!streams(output).some(s=>s.codec_type==='video'));assert.ok((await fs.stat(j.output)).size>0);
    for(const format of ['m4a','flac']){const audio=engine.add({url:base+'/one.mp4',type:'video',media:{quality:'audio',audioFormat:format}});const result=await done(audio.id);assert.ok(result.output.endsWith('.'+format),result.output);assert.ok(streams(result.output).some(s=>s.codec_type==='audio'));}
    if(process.env.ODM_LIVE_COLLECTION){const live=await engine.inspectCollection('https://www.youtube.com/@jawed/videos',5);assert.ok(live.entries.length>0);console.log('PASS live channel inspection:',live.title,live.entries.length,'entries');}
    console.log('PASS: actual yt-dlp collection, subtitle SRT, MKV remux, metadata, MP3 conversion, M4A/FLAC audio with FFprobe stream validation.');
  }finally{await engine.close();s.closeAllConnections();await new Promise(r=>s.close(r));await fs.rm(root,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
