const http=require('node:http'),crypto=require('node:crypto');
const sha=b=>crypto.createHash('sha256').update(b).digest('base64'),md5=b=>crypto.createHash('md5').update(b).digest('base64'),etag=b=>'"'+crypto.createHash('md5').update(b).digest('hex')+'"';
// r2: emulate Cloudflare R2, which rejects x-amz checksum headers and conditional multipart completion but validates Content-MD5.
async function cloudFixture({r2=false}={}){const objects=new Map(),uploads=new Map(),requests=[];let base,count=0,failPart=0,failChunk=0,badChecksum=false,loseCompletion=false;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,base),chunks=[];for await(const c of req)chunks.push(c);const data=Buffer.concat(chunks);requests.push({method:req.method,url:req.url,size:data.length,auth:!!req.headers.authorization,authorization:req.headers.authorization||'',range:req.headers['content-range']});const xml=(text,status=200)=>{res.writeHead(status,{'content-type':'application/xml'});res.end(text);},json=(v,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(v));};
if(u.pathname.startsWith('/upload/storage/v1/')){const metadata=JSON.parse(data);const id='gcs-'+(++count);uploads.set(id,{key:u.searchParams.get('name'),metadata,data:Buffer.alloc(0)});res.writeHead(200,{Location:base+'/session/'+id});return res.end();}
if(u.pathname.startsWith('/storage/v1/')){const key=decodeURIComponent(u.pathname.split('/o/')[1]||'');if(!key)return json({name:'fixture-bucket'});const object=objects.get(key);if(!object)return json({error:{code:404,message:'Missing'}},404);return json({name:key,size:String(object.data.length),md5Hash:badChecksum?'bad':md5(object.data),metadata:object.metadata.metadata});}
if(u.pathname.startsWith('/session/')){const id=u.pathname.split('/').at(-1),upload=uploads.get(id);if(!upload){res.writeHead(404);return res.end();}if(failChunk&&data.length&&--failChunk===0){res.writeHead(503);return res.end('fixture interruption');}if(data.length)upload.data=Buffer.concat([upload.data,data]);const total=Number((req.headers['content-range']||'').split('/').at(-1));if(upload.data.length===total){objects.set(upload.key,{data:upload.data,metadata:upload.metadata});return json({size:String(total)});}res.writeHead(308,upload.data.length?{Range:'bytes=0-'+(upload.data.length-1)}:{});return res.end();}
if(r2&&Object.keys(req.headers).some(h=>h.startsWith('x-amz-checksum-')||h==='x-amz-sdk-checksum-algorithm'))return xml('<Error><Code>NotImplemented</Code></Error>',501);if(req.headers['content-md5']&&req.headers['content-md5']!==md5(data))return xml('<Error><Code>BadDigest</Code></Error>',400);
const key=decodeURIComponent(u.pathname.split('/').slice(2).join('/'));if(req.method==='HEAD'){if(!key){res.writeHead(200);return res.end();}const object=objects.get(key);if(!object){res.writeHead(404);return res.end();}res.writeHead(200,{'content-length':object.data.length,'x-amz-meta-odm-sha256':object.hash,...(r2?{}:{'x-amz-checksum-sha256':badChecksum?'bad':object.checksum}),etag:r2&&badChecksum?'"bad"':object.etag});return res.end();}
if(req.method==='POST'&&u.searchParams.has('uploads')){const id='s3-'+(++count);uploads.set(id,{key,parts:new Map(),hash:req.headers['x-amz-meta-odm-sha256']});return xml('<InitiateMultipartUploadResult><UploadId>'+id+'</UploadId></InitiateMultipartUploadResult>');}
if(u.searchParams.has('uploadId')){const upload=uploads.get(u.searchParams.get('uploadId'));if(!upload)return xml('<Error><Code>NoSuchUpload</Code></Error>',404);if(req.method==='GET')return xml('<ListPartsResult><IsTruncated>false</IsTruncated>'+[...upload.parts].map(([n,p])=>`<Part><PartNumber>${n}</PartNumber><ETag>${p.etag}</ETag><Size>${p.data.length}</Size><ChecksumSHA256>${sha(p.data)}</ChecksumSHA256></Part>`).join('')+'</ListPartsResult>');if(req.method==='PUT'){const n=+u.searchParams.get('partNumber');if(failPart===n){failPart=0;return xml('<Error><Code>AccessDenied</Code></Error>',403);}upload.parts.set(n,{data,etag:etag(data)});res.writeHead(200,{etag:etag(data),...(r2?{}:{'x-amz-checksum-sha256':sha(data)})});return res.end();}if(req.method==='POST'){if(r2&&req.headers['if-none-match'])return xml('<Error><Code>NotImplemented</Code></Error>',501);const parts=[...upload.parts].sort((a,b)=>a[0]-b[0]).map(v=>v[1].data),body=Buffer.concat(parts),checksum=sha(Buffer.concat(parts.map(v=>Buffer.from(sha(v),'base64'))))+'-'+parts.length,tag='"'+crypto.createHash('md5').update(Buffer.concat(parts.map(v=>crypto.createHash('md5').update(v).digest()))).digest('hex')+'-'+parts.length+'"';objects.set(key,{data:body,hash:upload.hash,checksum,etag:tag});uploads.delete(u.searchParams.get('uploadId'));if(loseCompletion){loseCompletion=false;res.writeHead(500);return res.end('fixture lost completion response');}return xml('<CompleteMultipartUploadResult><ETag>'+tag+'</ETag>'+(r2?'':'<ChecksumSHA256>'+checksum+'</ChecksumSHA256>')+'</CompleteMultipartUploadResult>');}}
if(req.method==='PUT'){if(objects.has(key)){res.writeHead(412);return res.end();}objects.set(key,{data,hash:req.headers['x-amz-meta-odm-sha256'],checksum:req.headers['x-amz-checksum-sha256'],etag:etag(data)});res.writeHead(200,{etag:etag(data),...(r2?{}:{'x-amz-checksum-sha256':sha(data)})});return res.end();}res.writeHead(400);res.end('Unrecognized fixture request');
}catch(e){res.writeHead(500);res.end(e.message);}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;return {base,objects,uploads,requests,failPart:n=>failPart=n,failChunk:n=>failChunk=n,badChecksum:value=>badChecksum=value,loseCompletion:value=>loseCompletion=value,close:async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));}};}
module.exports={cloudFixture};
