const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const {Engine}=require('../src/engine.cjs');
async function fixture(t,options={}){const dir=await fsp.mkdtemp(path.join(os.tmpdir(),'odm-speed-'));const e=new Engine({dataDir:dir,downloadDir:path.join(dir,'downloads'),...options});t.after(async()=>{await e.close();await fsp.rm(dir,{recursive:true,force:true});});return e;}
async function until(fn){const end=Date.now()+15000;while(!await fn()){if(Date.now()>end)throw Error('Performance regression timed out');await new Promise(r=>setTimeout(r,10));}}
async function server(t,handler){const s=http.createServer(handler);await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(async()=>{s.closeAllConnections();await new Promise(r=>s.close(r));});return {s,url:`http://127.0.0.1:${s.address().port}`};}
test('asynchronous durable saves coalesce, keep the event loop free and flush the latest state before exit',async t=>{
 let release;const gate=new Promise(r=>release=r),write=fsp.writeFile;let writes=0;
 fsp.writeFile=async(...args)=>{if(String(args[0]).endsWith('state.json.tmp')){writes++;await gate;}return write(...args);};let e;
 try{e=await fixture(t,{asynchronousPersistence:true});for(let n=0;n<30;n++)e.add({url:`https://example.org/${n}`,start:false});let closed=false;const closing=e.close().then(()=>closed=true);await new Promise(r=>setTimeout(r,20));assert.equal(closed,false);assert.ok(e.stateWriter.pending);release();await closing;assert.equal(JSON.parse(await fsp.readFile(e.statePath,'utf8')).jobs.length,30);assert.ok(writes<=2,`Uncoalesced saves: ${writes}`);assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(e.statePath+'.bak','utf8')));}finally{release();fsp.writeFile=write;}
});
test('asynchronous save failure preserves history, reports it and recovers on the next save',async t=>{
 const e=await fixture(t,{asynchronousPersistence:true});await e.stateWriter.flush();const original=await fsp.readFile(e.statePath),rename=fsp.rename;
 fsp.rename=async(a,b)=>{if(b===e.statePath)throw Error('Disk temporarily unavailable');return rename(a,b);};try{e.add({url:'https://example.org/new',start:false});await e.stateWriter.flush();assert.match(e.persistenceWarning,/temporarily unavailable/);assert.deepEqual(await fsp.readFile(e.statePath),original);}finally{fsp.rename=rename;}e.save();await e.stateWriter.flush();assert.equal(e.persistenceWarning,'');assert.equal(JSON.parse(await fsp.readFile(e.statePath,'utf8')).jobs.length,1);
});
test('validated encrypted credentials are reused during restart instead of re-encrypting every job',async t=>{
 let seals=0;const options={encryptSecret:s=>{if(s.startsWith('{"headers"'))seals++;return Buffer.from(s).toString('base64');},decryptSecret:s=>Buffer.from(s,'base64').toString()};const e=await fixture(t,options);e.batch(()=>{for(let n=0;n<100;n++)e.add({url:`https://example.org/${n}`,start:false});});await e.close();seals=0;const reopened=new Engine({dataDir:e.dataDir,downloadDir:e.settings.downloadDir,...options});t.after(()=>reopened.close());assert.equal(reopened.jobs.length,100);assert.equal(seals,0);
});
test('HTTP probes and sequential requests reuse the same completed connection',async t=>{
 let connections=0;const {s,url}=await server(t,(req,res)=>{res.writeHead(206,{'content-length':1,'content-range':'bytes 0-0/123',etag:'"stable"'});res.end('x');});s.on('connection',()=>connections++);const {probe}=require('../src/net.cjs');await probe(url);await probe(url);await probe(url);assert.equal(connections,1);
});
test('balanced initial ranges and bounded writes preserve exact file bytes',async t=>{
 const data=Buffer.alloc(8*1024*1024,63),ranges=[];const {url}=await server(t,(req,res)=>{const m=/bytes=(\d+)-(\d+)/.exec(req.headers.range),start=+m[1],end=+m[2];if(end>0)ranges.push({start,end});res.writeHead(206,{'content-length':end-start+1,'content-range':`bytes ${start}-${end}/${data.length}`,etag:'"stable"'});res.end(data.subarray(start,end+1));});const e=await fixture(t);e.updateSettings({connections:8,retries:0,categorize:false});const open=fsp.open;let writes=0;fsp.open=async(...args)=>{const handle=await open(...args);if(String(args[0]).endsWith('.part')){const write=handle.write.bind(handle);handle.write=(...values)=>{writes++;return write(...values);};}return handle;};let j;try{j=e.get(e.add({url}).id);await until(()=>['complete','error'].includes(j.status));}finally{fsp.open=open;}assert.equal(j.status,'complete',j.error);assert.deepEqual(await fsp.readFile(j.output),data);assert.equal(ranges.slice(0,8).every(r=>r.end-r.start+1===data.length/8),true);assert.ok(writes<80,`Too many small disk writes: ${writes}`);
});
test('publication on the same filesystem avoids copying verified file bytes',async t=>{
 const e=await fixture(t);await fsp.mkdir(e.settings.downloadDir,{recursive:true});const source=path.join(e.dataDir,'source.bin');await fsp.writeFile(source,Buffer.alloc(1024*1024,97));const copy=fsp.copyFile;let copies=0;fsp.copyFile=async(...args)=>{copies++;return copy(...args);};let output;try{output=await require('../src/publication.cjs').publishFile(e,{filename:'output.bin',directory:e.settings.downloadDir,output:''},source);}finally{fsp.copyFile=copy;}assert.equal(copies,0);assert.deepEqual(await fsp.readFile(output),await fsp.readFile(source));await fsp.rm(source);assert.equal((await fsp.stat(output)).size,1024*1024);
});
test('server connection rejection falls back to one connection and completes without corrupting partial bytes',async t=>{
 const data=Buffer.alloc(4*1024*1024,83);let active=0,rejected=0;const {url}=await server(t,(req,res)=>{const m=/bytes=(\d+)-(\d+)/.exec(req.headers.range),start=+m[1],end=+m[2];if(end>0&&active>=2){rejected++;res.writeHead(429);res.end('Too many connections');return;}if(end>0)active++;let counted=end>0;res.on('close',()=>{if(counted){active--;counted=false;}});res.writeHead(206,{'content-length':end-start+1,'content-range':`bytes ${start}-${end}/${data.length}`,etag:'"stable"'});if(end===0){res.end(data.subarray(0,1));return;}setTimeout(()=>res.end(data.subarray(start,end+1)),40);});const e=await fixture(t);e.updateSettings({retries:2});const j=e.get(e.add({url}).id);await until(()=>['complete','error'].includes(j.status));assert.equal(j.status,'complete',j.error);assert.ok(rejected>0);assert.equal(j.connectionLimit,1);assert.deepEqual(await fsp.readFile(j.output),data);
});
test('redirect targets are resolved once and cross-origin credentials stay stripped for direct ranges',async t=>{
 let redirects=0,leaked=false;const data=Buffer.alloc(2*1024*1024,61);const second=await server(t,(req,res)=>{leaked ||= !!(req.headers.authorization||req.headers.cookie);const m=/bytes=(\d+)-(\d+)/.exec(req.headers.range),start=+m[1],end=+m[2];res.writeHead(206,{'content-length':end-start+1,'content-range':`bytes ${start}-${end}/${data.length}`,etag:'"stable"'});res.end(data.subarray(start,end+1));});const first=await server(t,(req,res)=>{redirects++;res.writeHead(302,{location:second.url});res.end();});const e=await fixture(t);const j=e.get(e.add({url:first.url,headers:{Authorization:'private',Cookie:'private'}}).id);await until(()=>['complete','error'].includes(j.status));assert.equal(j.status,'complete',j.error);assert.equal(redirects,1);assert.equal(leaked,false);assert.deepEqual(await fsp.readFile(j.output),data);
});
