const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {Engine}=require('../src/engine.cjs');
async function fixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'odm-smooth-'));const engine=new Engine({dataDir:dir,downloadDir:path.join(dir,'files')});t.after(async()=>{await engine.close();await fs.rm(dir,{recursive:true,force:true});});return engine;}
test('progress floods emit bounded deltas without writing history on every update; close saves the latest checkpoint',async t=>{const e=await fixture(t);const j=e.add({url:'https://example.org/file.bin',start:false});const raw=e.get(j.id);let writes=0,changes=0,progress=0;const save=e.save.bind(e);e.save=()=>{writes++;return save();};e.on('change',()=>changes++);e.on('progress',jobs=>{progress++;assert.equal(jobs.length,1);assert.equal(jobs[0].downloaded,999);});e.running.set(j.id,{controller:new AbortController(),promise:Promise.resolve()});for(let n=0;n<1000;n++){raw.downloaded=n;e.progressChanged();}await new Promise(r=>setTimeout(r,160));assert.equal(writes,0);assert.equal(changes,0);assert.equal(progress,1);e.running.clear();await e.close();assert.equal(JSON.parse(await fs.readFile(e.statePath,'utf8')).jobs[0].downloaded,999);assert.ok(writes<=2);});
test('torrent metadata and credentials never travel in renderer progress snapshots',async t=>{const e=await fixture(t),j=e.add({url:'https://example.org/a',start:false});Object.assign(e.get(j.id),{torrentData:'large metadata',headers:{Authorization:'secret'},cookies:[{value:'secret'}]});const publicJob=e.publicJob(e.get(j.id));assert.ok(!('torrentData' in publicJob));assert.ok(!('headers' in publicJob));assert.ok(!('cookies' in publicJob));});
test('closing an inspection cancels its child process and releases operation tracking',async t=>{const e=await fixture(t),controller=new AbortController();const promise=e.capture(process.execPath,['-e','setInterval(()=>{},1000)'],60000,controller.signal);assert.equal(e.children.size,1);controller.abort();await assert.rejects(promise,/Inspection cancelled/);assert.equal(e.children.size,0);assert.equal(e.captures.size,0);});
test('macOS tool resolution uses native executable names',()=>{const {toolPaths}=require('../src/platform.cjs');const mac=toolPaths('/Applications/ODM/tools','darwin');assert.ok(mac.ffmpeg.endsWith('ffmpeg'));assert.ok(mac.archive.endsWith('7zz'));assert.ok(mac.ytdlp.endsWith('yt-dlp'));assert.ok(!Object.values(mac).some(p=>p.endsWith('.exe')));});

test('a thousand playlist entries persist in one batch, preserve order and deduplicate after reload',async t=>{const e=await fixture(t);let writes=0,changes=0;const save=e.save.bind(e);e.save=()=>{writes++;return save();};e.on('change',()=>changes++);const entries=Array.from({length:1000},(_,n)=>({url:`https://example.org/video/${n}`,title:`Video ${n}`,index:n+1}));const start=performance.now();const result=e.addCollection({entries,title:'Large collection',start:false});const elapsed=performance.now()-start;assert.equal(result.added,1000);assert.equal(writes,1);assert.equal(changes,1);assert.equal(e.jobs[999].url,entries[999].url);const disk=JSON.parse(await fs.readFile(e.statePath,'utf8'));assert.equal(disk.jobs.length,1000);assert.equal(disk.jobs[999].id,e.jobs[999].id);assert.equal(e.addCollection({entries,title:'Large collection',start:false}).duplicates,1000);assert.equal(writes,1);await e.close();assert.equal(writes,2);console.log(`1,000 playlist imports: ${elapsed.toFixed(1)} ms, one save / snapshot`);});
test('nested batches save partial additions if an import encounters an invalid URL',async t=>{const e=await fixture(t);let writes=0;const save=e.save.bind(e);e.save=()=>{writes++;return save();};assert.throws(()=>e.batch(()=>{e.add({url:'https://example.org/a',start:false});e.batch(()=>e.add({url:'invalid',start:false}));}));assert.equal(writes,1);assert.equal(JSON.parse(await fs.readFile(e.statePath,'utf8')).jobs.length,1);assert.equal(e.batchDepth,0);});

test('bulk resume, pause and remove validate selection once and preserve completed output',async t=>{const e=await fixture(t);e.queues[0].enabled=false;const added=e.addCollection({title:'Batch controls',entries:Array.from({length:500},(_,n)=>({url:`https://example.org/${n}`,title:`Item ${n}`})),start:false});let writes=0;const save=e.save.bind(e);e.save=()=>{writes++;return save();};const ids=added.jobs.map(j=>j.id);assert.throws(()=>e.resumeMany([ids[0],'missing']),/no longer/);assert.equal(e.get(ids[0]).status,'paused');e.resumeMany(ids);assert.equal(writes,1);assert.ok(e.jobs.every(j=>j.status==='queued'));await e.pauseMany(ids);assert.equal(writes,2);assert.ok(e.jobs.every(j=>j.status==='paused'));const output=path.join(e.dataDir,'finished.txt');await fs.writeFile(output,'Keep this file');Object.assign(e.jobs[0],{status:'complete',output});await fs.mkdir(e.jobTemp(ids[1]),{recursive:true});await fs.writeFile(path.join(e.jobTemp(ids[1]),'part'),'partial');await e.removeMany(ids);assert.equal(writes,3);assert.equal(e.jobs.length,0);assert.equal(await fs.readFile(output,'utf8'),'Keep this file');await assert.rejects(fs.stat(e.jobTemp(ids[1])),{code:'ENOENT'});assert.equal(JSON.parse(await fs.readFile(e.statePath,'utf8')).jobs.length,0);});
