const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {Engine}=require('../src/engine.cjs');
const http=require('node:http');
async function until(fn,timeout=10000){const end=Date.now()+timeout;while(!await fn()){if(Date.now()>end)throw Error('Stability fixture timed out');await new Promise(r=>setTimeout(r,20));}}
async function server(t,handler){const s=http.createServer(handler);await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(async()=>{s.closeAllConnections();await new Promise(r=>s.close(r));});return {s,url:`http://127.0.0.1:${s.address().port}`};}
async function fixture(t,extra={}) { const dir=await fsp.mkdtemp(path.join(os.tmpdir(),'odm-stability-'));const options={dataDir:dir,downloadDir:path.join(dir,'files'),...extra};const engine=new Engine(options);t.after(async()=>{await engine.close();await fsp.rm(dir,{recursive:true,force:true});});return {dir,engine,options}; }
test('iteration 01: malformed history is quarantined before any partial state is applied',async t=>{
 const dir=await fsp.mkdtemp(path.join(os.tmpdir(),'odm-bad-state-'));t.after(()=>fsp.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'state.json');await fsp.writeFile(file,JSON.stringify({settings:{concurrent:999},jobs:{bad:true}}));const e=new Engine({dataDir:dir,downloadDir:path.join(dir,'files')});t.after(()=>e.close());assert.equal(e.settings.concurrent,2);assert.deepEqual(e.jobs,[]);assert.match(e.loadWarning,/could not be loaded/);assert.ok((await fsp.readdir(dir)).some(n=>n.includes('.unreadable-')));
});
test('iteration 02: a damaged primary history recovers complete jobs from a known-good backup',async t=>{
 const {engine:e,dir,options}=await fixture(t);const job=e.add({url:'https://example.org/a',start:false});await e.close();await fsp.writeFile(e.statePath,'{bad json');const restored=new Engine(options);t.after(()=>restored.close());assert.equal(restored.jobs[0].id,job.id);assert.match(restored.loadWarning,/Recovered/);assert.equal(JSON.parse(await fsp.readFile(path.join(dir,'state.json.bak'),'utf8')).jobs[0].id,job.id);
});
test('iteration 03: encryption and serialization failures retain the last valid history and report a save warning',async t=>{
 const {engine:e}=await fixture(t,{encryptSecret:s=>Buffer.from(s).toString('base64'),decryptSecret:s=>Buffer.from(s,'base64').toString()});const before=await fsp.readFile(e.statePath);e.encryptSecret=()=>{throw Error('Keychain unavailable');};e.secretCache.clear();assert.equal(e.save(),false);assert.match(e.persistenceWarning,/Keychain unavailable/);assert.deepEqual(await fsp.readFile(e.statePath),before);e.encryptSecret=s=>Buffer.from(s).toString('base64');e.settings.circular=e.settings;assert.equal(e.save(),false);assert.deepEqual(await fsp.readFile(e.statePath),before);delete e.settings.circular;assert.equal(e.save(),true);
});
test('iteration 04: repeated shutdown shares one operation and rejects new downloads',async t=>{
 const {engine:e}=await fixture(t);let saves=0;const save=e.save.bind(e);e.save=()=>{saves++;return save();};const first=e.close(),second=e.close();assert.equal(first,second);assert.throws(()=>e.add({url:'https://example.org/late'}),/shutting down/);await Promise.all([first,second]);assert.equal(saves,1);assert.equal(e.children.size,0);assert.equal(e.secretCache.size,0);
});
test('iteration 05: explicit resume clears stale automatic retry backoff for single and bulk controls',async t=>{
 const {engine:e}=await fixture(t);e.queues[0].enabled=false;const a=e.add({url:'https://example.org/a',start:false}),b=e.add({url:'https://example.org/b',start:false});for(const j of e.jobs){j.retryAt=Date.now()+3600000;j.retries=9;}e.resume(a.id);e.resumeMany([b.id]);assert.ok(e.jobs.every(j=>j.retryAt===0&&j.retries===0&&j.status==='queued'));
});
test('iteration 06: invalid schedules are rejected before mutation; ancient daily dates advance in bounded time',async t=>{
 const {engine:e}=await fixture(t);const before=JSON.stringify(e.queues);assert.throws(()=>e.setQueue({name:'Main download queue',enabled:false,startAt:'wrong'}),/schedule date/);assert.throws(()=>e.setQueue({name:null}),/queue name/);assert.equal(JSON.stringify(e.queues),before);const start=performance.now();e.setQueue({name:'Daily',daily:true,startAt:'0001-01-01T12:00:00Z'});assert.ok(Date.parse(e.queues.find(q=>q.name==='Daily').startAt)>Date.now());assert.ok(performance.now()-start<1000);
});
test('iteration 07: opening a partial file failure closes the HTTP response immediately',async t=>{
 let disconnected=false;const {url}=await server(t,(req,res)=>{res.on('close',()=>disconnected=true);res.writeHead(200);res.write(Buffer.alloc(65536));});const {engine:e}=await fixture(t);const j=e.get(e.add({url,start:false}).id);const open=fsp.open;fsp.open=async(...args)=>{if(String(args[0]).endsWith('.part'))throw Error('Disk denied');return open(...args);};try{await assert.rejects(e.transfer(j,{index:0,start:0,end:null,done:0},new AbortController().signal),/Disk denied/);}finally{fsp.open=open;}await until(()=>disconnected);
});
test('iteration 08: changed Last-Modified ranges cannot publish mixed file bytes',async t=>{
 const data=Buffer.alloc(8192,31);const {url}=await server(t,(req,res)=>{const m=/bytes=(\d+)-(\d+)/.exec(req.headers.range),start=+m[1],end=+m[2];res.writeHead(206,{'content-range':`bytes ${start}-${end}/${data.length}`,'content-length':end-start+1,'last-modified':start===0&&end===0?'Mon, 28 Sep 2026 00:00:00 GMT':'Tue, 29 Sep 2026 00:00:00 GMT'});res.end(data.subarray(start,end+1));});const {engine:e}=await fixture(t);e.updateSettings({retries:0,connections:1});const j=e.add({url});await until(()=>e.get(j.id).status==='error');assert.match(e.get(j.id).error,/Remote file changed/);assert.equal(e.get(j.id).checksum,'');
});
test('iteration 09: unsolicited content encoding fails instead of silently saving the wrong representation',async t=>{
 const {url}=await server(t,(req,res)=>{res.writeHead(200,{'content-encoding':'gzip'});res.end(require('node:zlib').gzipSync('wrong representation'));});await assert.rejects(require('../src/net.cjs').probe(url),/encoded content/);
});
test('iteration 10: redirect responses are closed even when their body never ends',async t=>{
 let closed=false;const {url}=await server(t,(req,res)=>{if(req.url==='/redirect'){res.on('close',()=>closed=true);res.writeHead(302,{location:'/file'});res.write('never ending body');}else res.end('done');});const response=await require('../src/net.cjs').request(url+'/redirect');let body='';for await(const chunk of response)body+=chunk;assert.equal(body,'done');await until(()=>closed);
});

test('iteration 12: publication stages bytes and survives a competing output name without overwriting it',async t=>{
 const {engine:e,dir}=await fixture(t);await fsp.mkdir(e.settings.downloadDir,{recursive:true});const source=path.join(dir,'source');await fsp.writeFile(source,'complete bytes');const job={filename:'published.bin',directory:e.settings.downloadDir,output:''};const link=fsp.link;let raced=false;fsp.link=async(a,b)=>{if(!raced&&path.basename(b)==='published.bin'){raced=true;await fsp.writeFile(b,'foreign bytes');}return link(a,b);};let output;try{output=await require('../src/publication.cjs').publishFile(e,job,source);}finally{fsp.link=link;}assert.equal(await fsp.readFile(output,'utf8'),'complete bytes');assert.equal(await fsp.readFile(path.join(job.directory,'published.bin'),'utf8'),'foreign bytes');assert.equal((await fsp.readdir(job.directory)).some(n=>n.endsWith('.partial')),false);
 const controller=new AbortController();controller.abort();await assert.rejects(require('../src/publication.cjs').publishFile(e,{filename:'cancelled.bin',directory:job.directory,output:''},source,controller.signal));assert.equal(fs.existsSync(path.join(job.directory,'cancelled.bin')),false);
 // Filesystems without hard links must also publish successfully and remove a failed reservation.
 const rename=fsp.rename;fsp.link=async()=>{throw Object.assign(Error('Hard links unsupported'),{code:'ENOTSUP'});};
 try{const fallback=await require('../src/publication.cjs').publishFile(e,{filename:'fallback.bin',directory:job.directory,output:''},source);assert.equal(await fsp.readFile(fallback,'utf8'),'complete bytes');fsp.rename=async()=>{throw Object.assign(Error('Rename denied'),{code:'EACCES'});};await assert.rejects(require('../src/publication.cjs').publishFile(e,{filename:'failed.bin',directory:job.directory,output:''},source),/Rename denied/);assert.equal(fs.existsSync(path.join(job.directory,'failed.bin')),false);}finally{fsp.link=link;fsp.rename=rename;}
 assert.equal((await fsp.readdir(job.directory)).some(n=>n.endsWith('.partial')),false);
});
test('iteration 13: cleanup and completion listeners cannot turn a verified file into a failed download',async t=>{
 const {url}=await server(t,(req,res)=>{const m=/bytes=(\d+)-(\d+)/.exec(req.headers.range||''),data=Buffer.from('done'),start=m?+m[1]:0,end=m?+m[2]:3;res.writeHead(m?206:200,{'content-length':end-start+1,etag:'"stable"',...(m?{'content-range':`bytes ${start}-${end}/4`}:{})});res.end(data.subarray(start,end+1));});const {engine:e}=await fixture(t);e.updateSettings({retries:0});e.on('complete',()=>{throw Error('Notification failed');});const rm=fsp.rm;fsp.rm=async(p,...args)=>{if(String(p).startsWith(e.tempDir)&&String(p)!==e.tempDir)throw Error('Temporary folder locked');return rm(p,...args);};let id;try{id=e.add({url,filename:'complete.bin'}).id;await until(()=>e.get(id).status==='complete'&&!e.running.size);}finally{fsp.rm=rm;}const j=e.get(id);assert.equal(j.retries,0);assert.equal(await fsp.readFile(j.output,'utf8'),'done');assert.match(j.cleanupWarning,/follow-up operation failed/);
});
test('iteration 14: capture bounds output, reports timeouts and decodes split UTF-8 correctly',async t=>{
 const {engine:e}=await fixture(t);await assert.rejects(e.capture(process.execPath,['-e','setInterval(()=>{},1000)'],100),/timed out/);await assert.rejects(e.capture(process.execPath,['-e',"process.stdout.write(Buffer.alloc(17*1024*1024,97))"],5000),/16 MB/);assert.equal(await e.capture(process.execPath,['-e',"const b=Buffer.from('🙂');process.stdout.write(b.subarray(0,2));setTimeout(()=>process.stdout.end(b.subarray(2)),20)"],5000),'🙂');assert.equal(e.children.size,0);assert.equal(e.captures.size,0);
});
test('iteration 15: video processes are tracked and accept their final unterminated output line',async t=>{
 const {engine:e}=await fixture(t);e.ytdlp=()=>process.execPath;e.videoArgs=()=>['-e',"const fs=require('fs');const a=process.argv;const out=a[a.indexOf('-o')+1].replace('%(ext)s','mp4');setTimeout(()=>{fs.writeFileSync(out,'video fixture');process.stdout.write('ODM_TITLE:Unicode 🙂\\nODM_FILE:'+out)},250)",'--'];const j=e.add({url:'https://example.org/video',type:'video'});await until(()=>e.children.size===1);await until(()=>e.get(j.id).status==='complete');assert.equal(await fsp.readFile(e.get(j.id).output,'utf8'),'video fixture');assert.match(e.get(j.id).filename,/Unicode/);await until(()=>!e.running.size);assert.equal(e.children.size,0);
});
async function bridge(t,e){const b=require('../src/bridge.cjs').createBridge(e,{port:0});const address=await b.listen();t.after(()=>b.close());return `http://127.0.0.1:${address.port}`;}
test('iteration 16: disconnecting a browser video inspection cancels its underlying operation',async t=>{
 const {engine:e}=await fixture(t);let started=false,cancelled=false;e.inspectVideo=(url,signal)=>new Promise((resolve,reject)=>{started=true;signal.addEventListener('abort',()=>{cancelled=true;reject(Error('Cancelled'));},{once:true});});const root=await bridge(t,e);const req=http.request(root+'/video-info',{method:'POST',headers:{'X-ODM-Token':e.token}},()=>{});req.on('error',()=>{});req.end(JSON.stringify({url:'https://example.org/video'}));await until(()=>started);req.destroy();await until(()=>cancelled);
});
test('iteration 17: invalid bridge batches add nothing and duplicate URLs add once',async t=>{
 const {engine:e}=await fixture(t);const root=await bridge(t,e);const post=urls=>fetch(root+'/batch',{method:'POST',headers:{'X-ODM-Token':e.token},body:JSON.stringify({urls,start:false})});assert.equal((await post(['https://example.org/a','bad url'])).status,400);assert.equal(e.jobs.length,0);assert.equal((await post([])).status,400);assert.equal(e.jobs.length,0);assert.equal((await post(['https://example.org/a','https://example.org/a'])).status,200);assert.equal(e.jobs.length,1);
});
test('iteration 18: malformed request targets return 400 while the bridge remains available',async t=>{
 const {engine:e}=await fixture(t);const root=await bridge(t,e);const u=new URL(root);const status=await new Promise((resolve,reject)=>{const req=http.request({hostname:u.hostname,port:u.port,path:'http://[',headers:{'X-ODM-Token':e.token}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});assert.equal(status,400);assert.equal((await fetch(root+'/health')).status,200);
});
test('iteration 19: archive inventory rejects invalid sizes and conflicting output names',()=>{
 const parse=require('../src/archive.cjs').parseListing;for(const size of ['-1','NaN','Infinity','9007199254740992'])assert.throws(()=>parse('Path = file.txt\nSize = '+size),/invalid entry size/);assert.throws(()=>parse('Path = file.txt\nSize = 1\n\nPath = FILE.txt\nSize = 2'),/duplicate output paths/);assert.equal(parse('Path = file.txt\nSize = 4')[0].size,4);
 assert.throws(()=>parse(Array.from({length:10001},(_,n)=>`Path = folder-${n}\nFolder = +\nSize = 0`).join('\n\n')),/10,000 entries/);
});
test('iteration 20: failed conversion leaves no output and successful conversion publishes exact bytes',async t=>{
 const {engine:e,dir}=await fixture(t);const id=e.add({url:'https://example.org/video.mp4',start:false}).id,j=e.get(id);await fsp.mkdir(j.directory,{recursive:true});j.output=path.join(j.directory,'original.mp4');j.status='complete';await fsp.writeFile(j.output,'original');e.capture=async(exe,args)=>{await fsp.writeFile(args.at(-1),'partial');throw Error('Encoder failed');};await assert.rejects(e.convertMedia(id,'mp3'),/Encoder failed/);assert.equal(fs.existsSync(path.join(j.directory,'original - converted.mp3')),false);assert.equal((await fsp.readdir(e.tempDir)).some(n=>n.startsWith('conversion-')),false);e.capture=async(exe,args)=>{await fsp.writeFile(args.at(-1),'complete converted bytes');};const output=await e.convertMedia(id,'mp3');assert.equal(await fsp.readFile(output,'utf8'),'complete converted bytes');assert.equal(await fsp.readFile(j.output,'utf8'),'original');assert.equal(e.processing.size,0);
});
test('iteration 21: duplicate torrent selections are stored once and detached from caller mutations',async t=>{
 const {engine:e}=await fixture(t);const selection=[0,0,1];const j=e.addTorrent({url:'magnet:?xt=urn:btih:0123456789012345678901234567890123456789',selection,start:false});selection.push(3);assert.deepEqual(e.get(j.id).torrentSelection,[0,1]);assert.throws(()=>e.addTorrent({url:'magnet:?xt=urn:btih:0123456789012345678901234567890123456789',selection:[-1],start:false}),/valid torrent files/);
});
test('iteration 22: damaged overlapping saved segments reset before resume and publish correct bytes',async t=>{
 const data=Buffer.from('0123456789');const {url}=await server(t,(req,res)=>{const m=/bytes=(\d+)-(\d+)/.exec(req.headers.range||''),start=m?+m[1]:0,end=m?+m[2]:9;res.writeHead(m?206:200,{'content-length':end-start+1,etag:'"stable"',...(m?{'content-range':`bytes ${start}-${end}/10`}:{})});res.end(data.subarray(start,end+1));});const {engine:e}=await fixture(t);const j=e.get(e.add({url,filename:'segments.bin',start:false}).id);j.size=10;j.etag='"stable"';j.segments=[{index:0,start:0,end:4,done:5},{index:1,start:0,end:4,done:5}];await fsp.mkdir(e.jobTemp(j.id),{recursive:true});for(let i=0;i<2;i++)await fsp.writeFile(path.join(e.jobTemp(j.id),i+'.part'),data.subarray(0,5));e.resume(j.id);await until(()=>j.status==='complete');assert.deepEqual(await fsp.readFile(j.output),data);
});
